import type { IMasterAccount } from "@/types/masters/masterChartOfAccount";
import type { IMasterPartner } from "@/types/masters/masterPartner";

export interface IGeneralSettingSales {
  id: string;
  generalsetting_id: string;
  generalsettingsell_piutang_id: string | null;
  generalsettingsell_unbill_id: string | null;
  generalsettingsell_unbillrevenue_id: string | null;
  generalsettingsell_uangmuka_id: string | null;
  generalsettingsell_uangmukaorder_id: string | null;
  generalsettingsell_bg_id: string | null;
  generalsettingsell_ppn_id: string | null;
  generalsettingsell_defaultmasterpartner_id: string | null;
  generalsettingsell_cardcharges: string | null;
  generalsettingsell_selisihretur_id: string | null;
  masterbussiness_id: string;
  generalsettingsell_priceperpiece: boolean;
  generalsettingsell_bgpotongpiutang: boolean;
  generalsettingsell_cekplafonquote: boolean;
  generalsettingsell_cekplafonorder: boolean;
  generalsettingsell_cekplafon: boolean;
  generalsettingsell_quotemaxitem: number;
  generalsettingsell_ordermaxitem: number;
  generalsettingsell_invoicemaxitem: number;
  generalsettingsell_quotedirectprint: boolean;
  generalsettingsell_orderdirectprint: boolean;
  generalsettingsell_invoicedirectprint: boolean;
  generalsettingsell_returdirectprint: boolean;
  generalsettingsell_quotetypeprint: boolean;
  generalsettingsell_ordertypeprint: boolean;
  generalsettingsell_invoicetypeprint: boolean;
  generalsettingsell_returtypeprint: boolean;
  generalsettingsell_ubahhargatarikquoteorder: boolean;
  generalsettingsell_ubahhargatarikorderfaktur: boolean;
  generalsettingsell_ubahdisctarikquoteorder: boolean;
  generalsettingsell_ubahdisctarikorderfaktur: boolean;
  generalsettingsell_ubahhargaquote: boolean;
  generalsettingsell_ubahhargaorder: boolean;
  generalsettingsell_ubahdiscquote: boolean;
  generalsettingsell_ubahdiscorder: boolean;
  generalsettingsell_ubahhargainvoice: boolean;
  generalsettingsell_ubahdiscinvoice: boolean;
  generalsettingsell_notabanner: string;
  sales_piutang?: IMasterAccount | null;
  sales_unbill?: IMasterAccount | null;
  sales_unbillrevenue?: IMasterAccount | null;
  sales_uangmuka?: IMasterAccount | null;
  sales_uangmukaorder?: IMasterAccount | null;
  sales_bg?: IMasterAccount | null;
  sales_selisihretur?: IMasterAccount | null;
  sales_ppn?: IMasterAccount | null;
  default_customer?: IMasterPartner | null;
}
