import { type MyPage } from "@/components/layouts/layoutTypes";
import { Box, Button, Typography } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";

const PageError500: MyPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>PTNQ | Internal Server Error</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
          minHeight: "100vh",
        }}
      >
        <Typography variant="h1">500</Typography>
        <Typography variant="h4">Internal Server Error.</Typography>
        <Typography variant="h6">
          The page you’re looking for is not found. Please enter correct page.
        </Typography>
        <Button onClick={() => void router.push("/")}>Back Home</Button>
      </Box>
    </>
  );
};

export default PageError500;
PageError500.Layout = "Plain";
